(let ([x1 (read)])
  (let ([x2 (read)])
    (let ([x3 (read)])
      (let ([x4 (read)])
        (let ([x5 (read)])
          (let ([x6 (+ (read) 10)])
            (let ([x7 (- (read) 100)])
              (let ([x8 (read)])
                (let ([x11 (read)])
                  (let ([x12 (read)])
                    (let ([x13 (read)])
                      (let ([x14 (read)])
                        (let ([x15 (read)])
                          (let ([x16 (+ (read) 10)])
                            (let ([x17 (- (read) 100)])
                              (let ([x18 (read)])
                                (let ([x21 (read)])
                                  (let ([x22 (read)])
                                    (let ([x23 (read)])
                                      (let ([x24 (read)])
                                        (let ([x25 (read)])
                                          (let ([x26 (+ (read) 10)])
                                            (let ([x27 (- (read) 100)])
                                              (let ([x28 (read)])
											  	(+ x1 (+ x2 (+ x3 (+ x4 (+ x5 (+ x6 (+ x8 
												(+ x11 (+ x12 (+ x13 (+ x14 (+ x15 (+ x16 (+ x18
												(+ x21 (+ x22 (+ x23 (+ x24 (+ x25 (+ x26 x28))))))))))))))))))))))))))))))))))))))))))))
